# Wikidata 10
[wikidata_10_cc]
campaign_tracking = "WMDE_wikidata_10_cc_2022"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org_wikidata_10_cc"

[wikidata_10_cc.banners.ctrl]
filename = "./wikidata_10_cc/banner_ctrl.js"
pagename = "B22WMDE_wikidata_10_cc"
tracking = "WMDE_wikidata_10_cc"

[wikidata_10_cc_monobook]
campaign_tracking = "WMDE_wikidata_10_cc_2022"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=monobook&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org_wikidata_10_cc"

[wikidata_10_cc_monobook.banners.ctrl]
filename = "./wikidata_10_cc/banner_ctrl.js"
pagename = "B22WMDE_wikidata_10_cc_monobook"
tracking = "WMDE_wikidata_10_cc_monobook"

[wikidata_10_cc_minerva]
campaign_tracking = "WMDE_wikidata_10_cc_2022"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=Minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org_wikidata_10_cc"

[wikidata_10_cc_minerva.banners.ctrl]
filename = "./wikidata_10_cc/banner_ctrl.js"
pagename = "B22WMDE_wikidata_10_cc_minerva"
tracking = "WMDE_wikidata_10_cc_minerva"

[wikidata_10_cc_timeless]
campaign_tracking = "WMDE_wikidata_10_cc_2022"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=timeless&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org_wikidata_10_cc"

[wikidata_10_cc_timeless.banners.ctrl]
filename = "./wikidata_10_cc/banner_ctrl.js"
pagename = "B22WMDE_wikidata_10_cc_timeless"
tracking = "WMDE_wikidata_10_cc_timeless"

# Carto-Season
[carto_week]
campaign_tracking = "WMDE_carto_week_2022"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[carto_week.banners.ctrl]
filename = "./carto_season/banner_ctrl.js"
pagename = "B22WMDE_carto_week"
tracking = "WMDE_carto_week"

[carto_week_monobook]
campaign_tracking = "WMDE_carto_week"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=monobook&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[carto_week_monobook.banners.ctrl]
filename = "./carto_season/banner_ctrl.js"
pagename = "B22WMDE_carto_week_b1_monobook"
tracking = "WMDE_carto_week_b1_monobook"

[carto_week_minerva]
campaign_tracking = "WMDE_carto_week"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=Minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[carto_week_minerva.banners.ctrl]
filename = "./carto_season/banner_ctrl.js"
pagename = "B22WMDE_carto_week_b1_minerva"
tracking = "WMDE_carto_week_b1_minerva"

[carto_week_timeless]
campaign_tracking = "WMDE_carto_week"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=timeless&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[carto_week_timeless.banners.ctrl]
filename = "./carto_season/banner_ctrl.js"
pagename = "B22WMDE_carto_week_b1_timeless"
tracking = "WMDE_carto_week_b1_timeless"

# Wikipedia-Paidwriting
[paidwriting]
campaign_tracking = "WMDE_paid_editing_survey"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[paidwriting.banners.ctrl]
filename = "./wikipedia_paidwriting/banner_ctrl.js"
pagename = "B22WMDE_paid_editing_survey"
tracking = "WMDE_paid_editing_survey"

[paidwriting_monobook]
campaign_tracking = "WMDE_paid_editing_survey"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=monobook&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[paidwriting_monobook.banners.ctrl]
filename = "./wikipedia_paidwriting/banner_ctrl.js"
pagename = "B22WMDE_paid_editing_survey_b1_monobook"
tracking = "WMDE_paid_editing_survey_b1_monobook"

[paidwriting_minerva]
campaign_tracking = "WMDE_paid_editing_survey"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=Minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[paidwriting_minerva.banners.ctrl]
filename = "./wikipedia_paidwriting/banner_ctrl.js"
pagename = "B22WMDE_paid_editing_survey_b1_minerva"
tracking = "WMDE_paid_editing_survey_b1_minerva"

[paidwriting_timeless]
campaign_tracking = "WMDE_paid_editing_survey"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=timeless&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[paidwriting_timeless.banners.ctrl]
filename = "./wikipedia_paidwriting/banner_ctrl.js"
pagename = "B22WMDE_paid_editing_survey_b1_timeless"
tracking = "WMDE_paid_editing_survey_b1_timeless"

# Wikipedia-Aktionswoche
[aktionswoche]
campaign_tracking = "WMDE_wp20_aw"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[aktionswoche.banners.ctrl]
filename = "./wikipedia_aktionswoche/banner_ctrl.js"
pagename = "B21WMDE_wp20_aw_b1_desktop"
tracking = "WMDE_wp20_aw_b1_desktop"

[aktionswoche.banners.var]
filename = "./wikipedia_aktionswoche/banner_var.js"
pagename = "B21WMDE_wp20_aw_b2_desktop"
tracking = "WMDE_wp20_aw_b2_desktop"

[aktionswoche_mobile]
campaign_tracking = "WMDE_wp20_aw"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=Minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[aktionswoche_mobile.banners.ctrl]
filename = "./wikipedia_aktionswoche/banner_ctrl.js"
pagename = "B21WMDE_wp20_aw_b1_mobile"
tracking = "WMDE_wp20_aw_b1_mobile"

[aktionswoche_mobile.banners.var]
filename = "./wikipedia_aktionswoche/banner_var.js"
pagename = "B21WMDE_wp20_aw_b2_mobile"
tracking = "WMDE_wp20_aw_b2_mobile"

[aktionswoche_ipad]
campaign_tracking = "WMDE_wp20_aw"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=Minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[aktionswoche_ipad.banners.ctrl]
filename = "./wikipedia_aktionswoche/banner_ctrl.js"
pagename = "B21WMDE_wp20_aw_b1_ipad"
tracking = "WMDE_wp20_aw_b1_ipad"

[aktionswoche_ipad.banners.var]
filename = "./wikipedia_aktionswoche/banner_var.js"
pagename = "B21WMDE_wp20_aw_b2_ipad"
tracking = "WMDE_wp20_aw_b2_ipad"

# Wikipedia-Challenge
[challenge]
campaign_tracking = "WMDE_neweditors_autumn_2019"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[challenge.banners.ctrl]
filename = "./wikipedia_challenge/banner_ctrl.js"
pagename = "B20WMDE_challengebnr_fall2020_ctrl"
tracking = "WMDE_challengebnr_fall2020_ctrl"

[challenge.banners.var]
filename = "./wikipedia_challenge/banner_var.js"
pagename = "B20WMDE_challengebnr_fall2020_var"
tracking = "WMDE_challengebnr_fall2020_var"

[challenge_mobile]
campaign_tracking = "WMDE_neweditors_autumn_2019_m"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=Minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[challenge_mobile.banners.var]
filename = "./wikipedia_challenge/banner_var.js"
pagename = "B20WMDE_challengebnr_fall2020_var_m"
tracking = "WMDE_challengebnr_fall2020_var_m"

[challenge_mobile.banners.ctrl]
filename = "./wikipedia_challenge/banner_ctrl.js"
pagename = "B20WMDE_challengebnr_fall2020_ctrl_m"
tracking = "WMDE_challengebnr_fall2020_ctrl_m"

# Occasional Editors Campaign
[occasional]
campaign_tracking = "WMDE_oceditors_fall_2021"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[occasional.banners.ctrl]
filename = "./occasional_editors/banner_ctrl.js"
pagename = "B21WMDE_oceditors_fall_2021"
tracking = "WMDE_oceditors_fall_2021_ctrl"

# Techwish Campaign
[techwish]
campaign_tracking = "WMDE_techwish_survey_2022"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[techwish.banners.main]
filename = "./techwish/main.js"
pagename = "B22WMDE_techwish_survey_2022"
#tracking string gets extended with a suffix in the code
tracking = "WMDE_techwish_survey_2022"


# Authors Campaign
[authors]
campaign_tracking = "WMDE_neweditors_autumn_2019"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[authors.banners.autumn]
filename = "./authors/banner.js"
pagename = "B19WMDE_neweditors_autumn_2019_lp1"
tracking = "WMDE_neweditors_autumn_2019_lp1"

# Authors Campaign Mobile for easily testing mobile view
[authors_mobile]
campaign_tracking = "WMDE_neweditors_autumn_2019m"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[authors_mobile.banners.autumn]
filename = "./authors/banner_mobile.js"
pagename = "B19WMDE_neweditors_autumn_2019_lp1m"
tracking = "WMDE_neweditors_autumn_2019_lp1m"
